[package]
name = "remote-evdev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.11.4"
ron = "*"
byteorder = "1.4.3"
nix = "0.24.2"

[patch.crates-io]
evdev = { path = "evdev" }